version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vpn-mini-app
    restart: unless-stopped
    ports:
      - "8001:8000"
    volumes:
      - ./:/var/www
    networks:
      - vpn-mini-network

networks:
  vpn-mini-network:
    driver: bridge
