version: '3.8'
services:
  app:
    build: .
    container_name: vpn-admin-dev
    user: "${UID:-1000}:${GID:-1000}"
#    ports:
#      - "8001:8000"
    volumes:
      - .:/var/www
    environment:
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/database/database.sqlite
    networks:
      - vpn-net
  nginx:
    image: nginx:alpine
    container_name: vpn-admin-nginx
    ports:
      - "8001:80"
    volumes:
      - .:/var/www
      - ./docker-nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - vpn-net

networks:
  vpn-net:
    driver: bridge
